version: "3.9"

services:
  
  postgres:
    image: postgres:17

    container_name: taskflow-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
      POSTGRES_DB: taskflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data:
